<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $report['title'] }}</title>
    <style>
        @page { margin: 28px 28px 36px; }
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            color: #1f2937;
            font-size: 12px;
            line-height: 1.45;
            background: #f8fafc;
        }
        .page {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 14px;
            padding: 24px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 2px solid #0f172a;
            padding-bottom: 16px;
            margin-bottom: 18px;
        }
        .brand {
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: .14em;
            color: #64748b;
            margin-bottom: 6px;
        }
        h1 {
            margin: 0;
            font-size: 26px;
            color: #0f172a;
        }
        .subtle { color: #64748b; }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 12px;
            margin: 18px 0 22px;
        }
        .card {
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            padding: 14px;
            background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
        }
        .card .label { font-size: 10px; text-transform: uppercase; color: #64748b; letter-spacing: .12em; }
        .card .value { font-size: 22px; font-weight: 700; color: #0f172a; margin-top: 6px; }
        .section { margin-top: 18px; page-break-inside: avoid; }
        .section-title {
            font-size: 14px;
            font-weight: 700;
            color: #0f172a;
            margin: 0 0 10px;
        }
        table { width: 100%; border-collapse: collapse; }
        th, td {
            border: 1px solid #e2e8f0;
            padding: 9px 10px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background: #0f172a;
            color: #ffffff;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: .08em;
        }
        tfoot td { font-weight: 700; }
        .footer {
            margin-top: 18px;
            padding-top: 12px;
            border-top: 1px solid #e2e8f0;
            font-size: 11px;
            color: #64748b;
            display: flex;
            justify-content: space-between;
        }
        .empty {
            border: 1px dashed #cbd5e1;
            border-radius: 10px;
            padding: 14px;
            color: #64748b;
            background: #f8fafc;
        }
    </style>
</head>
<body>
<div class="page">
    <div class="header">
        <div>
            <div class="brand">Enterprise Report</div>
            <h1>{{ $report['title'] }}</h1>
            <div class="subtle">{{ $report['company']['name'] }} • {{ $report['period']['label'] }}</div>
        </div>
        <div class="subtle" style="text-align:right;">
            <div>Generated</div>
            <div style="font-weight:700;color:#0f172a;">{{ $report['generated_at'] }}</div>
        </div>
    </div>

    <div class="summary-grid">
        @foreach($report['summary_cards'] as $card)
            <div class="card">
                <div class="label">{{ $card['label'] }}</div>
                <div class="value">{{ $card['value'] }}</div>
            </div>
        @endforeach
    </div>

    @foreach($report['sections'] as $section)
        <div class="section">
            <div class="section-title">{{ $section['title'] }}</div>
            @if(empty($section['rows']))
                <div class="empty">No records were found for this section in the selected period.</div>
            @else
                <table>
                    <thead>
                    <tr>
                        @foreach($section['headers'] as $header)
                            <th>{{ $header }}</th>
                        @endforeach
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($section['rows'] as $row)
                        <tr>
                            @foreach($row as $cell)
                                <td>{{ $cell }}</td>
                            @endforeach
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    @endforeach

    <div class="footer">
        <span>Generated by the SaaS reporting system.</span>
        <span>{{ now()->format('Y-m-d H:i') }}</span>
    </div>
</div>
</body>
</html>
